spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.2:8848
  application:
    name: pacmall-cart
  thymeleaf:
    cache: false
  redis:
    host: 192.168.1.2
server:
  port: 22200

