spring:
  datasource:
    username: root
    password: xwh12138
    url: jdbc:mysql://192.168.1.2:3306/pacmall_ums?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.2:8848
  application:
    name: pacmall-member

mybatis-plus:
  mapper-locations: classpath:/maaper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000