spring:
  datasource:
    username: root
    password: xwh12138
    url: jdbc:mysql://192.168.1.2:3306/pacmall_ums?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.2:8848
    gateway:
      routes:
        # http://localhost:88/api/product/category/list/tree
        # http://localhost:10000/product/category/list/tree
        - id: product_route
          uri: lb://pacmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
          # http://localhost:20000/oss/policy
          # http://localhost:88/api/thirdparty/oss/policy
        - id: third_party_route
          uri: lb://pacmall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://pacmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://pacmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        # 域名跳转
        - id: pacmall_host_route
          uri: lb://pacmall-product
          predicates:
            - Host=pacmall.com,item.pacmall.com

        - id: pacmall_auth_route
          uri: lb://pacmall-auth-server
          predicates:
            - Host=auth.pacmall.com

        - id: pacmall_cart_route
          uri: lb://pacmall-cart
          predicates:
            - Host=cart.pacmall.com

        - id: pacmall_order_route
          uri: lb://pacmall-order
          predicates:
            - Host=order.pacmall.com

        - id: pacmall_member_route
          uri: lb://pacmall-member
          predicates:
            - Host=member.pacmall.com

        - id: pacmall_search_route
          uri: lb://pacmall-search
          predicates:
            - Host=search.pacmall.com

        - id: pacmall_seckill_route
          uri: lb://pacmall-seckill
          predicates:
            - Host=seckill.pacmall.com

## 前端项目，/api
## http://localhost:88/api/captcha.jpg
## http://localhost:8080/renren-fast/captcha.jpg

#mybatis-plus:
#  mapper-locations: classpath:/maaper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

server:
  port: 88