spring:
  datasource:
    username: root
    password: xwh12138
    url: jdbc:mysql://192.168.1.2:3306/pacmall_pms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.2:8848
    alicloud:
      access-key: LTAI5tHduJ3gp7DamKH4Hyyr
      secret-key: wk6eSDLoOR7WigwhGoJPuhP5Jtq4HA
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
  application:
    name: pacmall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/maaper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 10000

logging:
  level:
    com.patrick.pacmall: debug
