spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.2:8848
    alicloud:
      access-key:
      secret-key: 
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: pacmall

  application:
    name: pacmall-third-party
server:
  port: 20000